/*

After insert
Soslsearch transaction number + trigger.size set loyalty discount with conditional

*/
public class TransactionTrigger{
    public static void updateLoyaltyDiscount(List<Transaction> newTransactions){
        for(transaction newTransaction: newTransactions){
            //pull out unique accounts
            //make accountUpdated list.
            //send that account to update.
        }
    }
}